AQUI VAI GUIAR O USUÁRIO PARA ALGUMAS DESCRIÇÕES MAIS ESPECÍFICAS SOBRE O LIVRO, COMO A DESCRIÇÃO E O USUÁRIO QUE ADICIONOU O LIVRO POR EXEMPLO.
IMAGINO QUE VAI TER UM BOTÃO PARA VOLTAR PARA A GALERIA DE LIVROS, E TALVEZ UM BOTÃO PARA EDITAR O LIVRO, MAS ESSE BOTÃO SÓ VAI APARECER SE O USUÁRIO ESTIVER LOGADO
E FOR O USUÁRIO QUE ADICIONOU O LIVRO, POR EXEMPLO.