É UMA PARTE MAIS "CENTRAL" DO SITE, ONDE VAI TER ALGUMAS INFORMAÇÕES SOBRE O PROJETO, COMO ELE FUNCIONA, POR QUE A GALERIA DE LIVRO, ETC...

EU IMAGINO TENDO INFORMAÇÕES SOBRE O PROJETO, 
COMO ELE FUNCIONA E QUEM SÃO OS AUTORES(NÓS).

TAMBÉM VAI PERMITIR NAVEGAÇÃO PARA AS OUTRAS PÁGINAS, TAL QUAL O INDEX VAI FAZER INICIALMENTE E O CABEÇALHO VAI PERMITIR DEPOIS.