AQUI POSSIVELMENTE ESTARÁ A VALIDAÇÃO DO LOGIN, UTILIZANDO DO USUARIO.PHP QUE ESTA MAIS ACIMA.

É SOMENTE A PARTIR DESTA TELA QUE SERAM LIBERADAS AS OPÇÕES DE EDIÇÃO PRESENTES NA LIVRO.PHP, COMO CADASTRAR, EDITAR E EXCLUIR LIVROS, POR EXEMPLO.

SERIA INTERESSANTE TAMBÉM PERMITIR A OPÇÃO DA PESSOA SE CADASTRAR NO SITE, CASO "NÃO TENHA UMA CONTA"

OS COOKIES E SESSIONS EU AINDA ESTOU NA DÚVIDA SE SERÃO IMPLEMENTADAS AQUI OU SE VÃO FICAR PARA A CLASSE USUÁRIO, MAS DE QUALQUER FORMA ESSA É A PARTE QUE
VAI PERMITIR O USUÁRIO FICAR LOGADO E ACESSAR AS FUNÇÕES DE EDIÇÃO DO SITE.