ESTA PROVAVELMENTE SERIA A PRÓXIMA PARTE FEITA, COM O NOME, REDES SOCIAIS E O LOGO E TALVEZ UM ATALHO PARA A HOME(ONDE EU IMAGINO TENDO INFORMAÇÕES SOBRE O PROJETO, 
COMO ELE FUNCIONA E QUEM SÃO OS AUTORES(NÓS)). 
